# Generated by Django 4.2.1 on 2024-08-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Uživatelská role', 'verbose_name_plural': 'Uživatelské role'},
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrátor'), ('agent', 'Pojistitel'), ('insured', 'Pojištěnec')], default='insured', max_length=20),
        ),
    ]
